### ISSUE TITLE
[JOSS Review] Example Usage

### ISSUE THREAD

**Issue by mbeyss** [xianggebenben/GraphSL#14]
related to this [JOSS Review](https://github.com/openjournals/joss-reviews/issues/6796)

While you have a very nice example that shows how to use all of your algorithms it could really need some comments and structure. I would suggest turning this into a jupyter notebook, where you can better explain and show what you are doing.

**Comment by xianggebenben** [comment]
Thank you for the suggestion. We have added a jupyter notebook file [tutorial.ipynb](https://github.com/xianggebenben/GraphSL/blob/main/tutorial.ipynb) to explain the implementation.

**Comment by mbeyss** [comment]
That notebook is a good first step. What I hoped for was some added comments. Notebooks offer great ways of structuring and commenting code

**Comment by xianggebenben** [comment]
> That notebook is a good first step. What I hoped for was some added comments. Notebooks offer great ways of structuring and commenting code

Thank you for the comment. The jupyter notebook file [tutorial.ipynb](https://github.com/xianggebenben/GraphSL/blob/main/tutorial.ipynb) is added with detailed comments of explanations. Please let me know if you have any questions.

**Comment by mbeyss** [comment]
I think the features of a notebook can be better employed. I created a pull request, to show what I mean. Have a look at #17

**Comment by xianggebenben** [comment]
> I think the features of a notebook can be better employed. I created a pull request, to show what I mean. Have a look at #17

Thanks very much for your help. I have merged the pull request.
