### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by waityousea** [xianggebenben/GraphSL#9]
你好，很高兴看到您的成果。在GraphSL的方法中，您提供了8个基准数据集，请问这些数据集是怎么生成的，能否给出相应的方法？

**Comment by xianggebenben** [comment]
Thank you for your interest in our library. Among eight datasets, memet8000 and diagg16000 provide the true source-diffusion pairs; for the other datasets, we can generate the diffusion by "diffusion_generation", as shown by the following example:

curr_dir = os.getcwd()
data_name = 'karate'  # 'karate', 'dolphins', 'jazz', 'netscience', 'cora_ml', 'power_grid'
graph = load_dataset(data_name,curr_dir)
dataset = diffusion_generation(graph=graph, infect_prob=0.3, diff_type='IC', sim_num=100, seed_ratio=0.3)

Please let me know if you have any questions. Thanks.
